//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Path_Finder
{
	public class Cell
	{
		public bool isObstical{ get; set; }
		public int RowPosition{ get; set; }
		public int ColumnPosition{ get; set; }
		public bool hasSteppedOn { get; set; }
		public List<Cell> cellNeighbors = new List<Cell>();
		public bool isWall { get; set; }

		public Cell ()
		{
			isWall = false;
			isObstical = false;
		}

		public Cell Clone()
		{
			Cell cell = new Cell();
			cell.ColumnPosition = this.ColumnPosition;
			cell.RowPosition = this.RowPosition;
			cell.isObstical = this.isObstical;
			cell.hasSteppedOn = this.hasSteppedOn;
			cell.cellNeighbors = this.cellNeighbors;
			cell.isWall = this.isWall;
			return cell;
		}

		public void SetNeighbors(Grid grid)
		{
			cellNeighbors.Clear();
			//1 = top
			//2 = bottom
			//3 = left
			//4 = right

			for (int i = 0; i < 4; i++)
			{
				try
				{
					if (i == 0)
					{
						Cell cellNeigh = grid[RowPosition - 1, ColumnPosition];
						cellNeighbors.Add(cellNeigh);
					}
					else if (i == 1)
					{
						Cell cellNeigh = grid[RowPosition + 1, ColumnPosition];
						cellNeighbors.Add(cellNeigh);
					}
					else if (i == 2)
					{
						Cell cellNeigh = grid[RowPosition, ColumnPosition - 1];
						cellNeighbors.Add(cellNeigh);
					}
					else if (i == 3)
					{
						Cell cellNeigh = grid[RowPosition, ColumnPosition + 1];
						cellNeighbors.Add(cellNeigh);
					}
				}
				catch (Exception)
				{
					Cell cellWall = new Cell();
					cellWall.isWall = true;
					cellNeighbors.Add(cellWall);
				}

			}
		}

		//public void SetNeighbors()
		//{
		//	cellNeighbors = new Cell[3,3];
		//}

	}
}

