//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Windows.Forms;

namespace Path_Finder
{
	public class Grid
	{
		public int Height { get; set;}
		public int Width { get; set; }

		public Cell[,] grid;

		public Grid ()
		{

		}

		public Cell this[int x, int y]
		{
			get { return grid[x, y]; }
		}
        /// <summary>
        /// Get the x, y of the cell. if it's negative it means it's on the edge so it needs to transition to the otherside of the grid.
        /// </summary>
        /// <param name="x"></param>
        /// <param name="y"></param>
        /// <returns></returns>
        /// 
        public Cell GetCell(int x, int y)
        {
            x = checkXLocation(x);
            y= checkYLocation(y);
            return grid[x, y];
        }

        public int checkXLocation(int x)
        {
            if (x < 0)
                return Width - 1;

            if (x > Width - 1)
                return 0;

            return x;
        }

        public int checkYLocation(int y)
        {
            if (y < 0)
                return Height - 1;

            if (y > Height - 1)
                return 0;

            return y;
        }

        public void NewGrid(int height, int width)
		{

            Height = height;
            Width = width;
			grid = new Cell[height, width];
            for (int i = 0; i < height; i++)
            {
                for (int x = 0; x < width; x++)
                {
                    Cell cell = new Cell(grid)
                    {
                        Coordinates = new Point
                        {
                            X = i,
                            Y = x
                        }
                    };
                    grid[i, x] = cell;
                }
            }
		}

		public void SetCell(Cell cell)
		{
            try
            {
                grid[cell.Coordinates.X, cell.Coordinates.Y] = cell;
            }
            catch (Exception)
            {

            }

		}

        public System.Data.DataTable GridAsDataTable()
        {
            DataTable dt = new DataTable();

            for (int column = 0; column < Width; column++)
            {
                dt.Columns.Add();
            }

            for (int row = 0; row < Height - 1; row++)
            {
                dt.Rows.Add();
            }

            return dt;
        }
		
	}
}

