//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
namespace Path_Finder
{
	public class Grid
	{
		public int Height { get; set;}
		public int Width { get; set; }
		public Cell[,] grid;

		public Grid ()
		{

		}

		public Cell this[int x, int y]
		{
			get { return grid[x, y]; }
		}

		public void NewGrid(int height, int width)
		{

            Height = height;
            Width = width;
			grid = new Cell[height, width];
            for (int i = 0; i < height; i++)
            {
                for (int x = 0; x < width; x++)
                {
                    Cell cell = new Cell()
                    {
                        RowPosition = i,
                        ColumnPosition = x
                    };
                    grid[i, x] = cell;
                }
            }
		}

		public void SetCell(Cell cell)
		{
            try
            {
                grid[cell.RowPosition, cell.ColumnPosition] = cell;
            }
            catch (Exception)
            {

            }

		}

        public System.Data.DataTable GridAsDataTable()
        {
            DataTable dt = new DataTable();

            for (int column = 0; column < Width; column++)
            {
                DataColumn col = dt.Columns.Add("Col" + column);
            }

            for (int row = 0; row < Height - 1; row++)
            {
                dt.Rows.Add();
            }

            return dt;
        }
		
	}
}

